[global]
   workgroup = WORKGROUP
   server string = PlayniteNASync
   security = user
   map to guest = Bad User
   dns proxy = no

[PlayniteNASync]
   path = /cache
   writable = yes
   browseable = yes
   guest ok = yes
   force user = root